# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: assets.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='assets.proto',
  package='taurustrade.model',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x61ssets.proto\x12\x11taurustrade.model\"8\n\tAssetUnit\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x11\n\tAccountID\x18\x03 \x01(\t\"7\n\tPortfolio\x12*\n\x04Unit\x18\x01 \x01(\x0b\x32\x1c.taurustrade.model.AssetUnit* \n\tDirection\x12\t\n\x05SHORT\x10\x00\x12\x08\n\x04LONG\x10\x01\x62\x06proto3'
)

_DIRECTION = _descriptor.EnumDescriptor(
  name='Direction',
  full_name='taurustrade.model.Direction',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SHORT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LONG', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=150,
  serialized_end=182,
)
_sym_db.RegisterEnumDescriptor(_DIRECTION)

Direction = enum_type_wrapper.EnumTypeWrapper(_DIRECTION)
SHORT = 0
LONG = 1



_ASSETUNIT = _descriptor.Descriptor(
  name='AssetUnit',
  full_name='taurustrade.model.AssetUnit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='taurustrade.model.AssetUnit.ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Name', full_name='taurustrade.model.AssetUnit.Name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='AccountID', full_name='taurustrade.model.AssetUnit.AccountID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=91,
)


_PORTFOLIO = _descriptor.Descriptor(
  name='Portfolio',
  full_name='taurustrade.model.Portfolio',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Unit', full_name='taurustrade.model.Portfolio.Unit', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=148,
)

_PORTFOLIO.fields_by_name['Unit'].message_type = _ASSETUNIT
DESCRIPTOR.message_types_by_name['AssetUnit'] = _ASSETUNIT
DESCRIPTOR.message_types_by_name['Portfolio'] = _PORTFOLIO
DESCRIPTOR.enum_types_by_name['Direction'] = _DIRECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AssetUnit = _reflection.GeneratedProtocolMessageType('AssetUnit', (_message.Message,), {
  'DESCRIPTOR' : _ASSETUNIT,
  '__module__' : 'assets_pb2'
  # @@protoc_insertion_point(class_scope:taurustrade.model.AssetUnit)
  })
_sym_db.RegisterMessage(AssetUnit)

Portfolio = _reflection.GeneratedProtocolMessageType('Portfolio', (_message.Message,), {
  'DESCRIPTOR' : _PORTFOLIO,
  '__module__' : 'assets_pb2'
  # @@protoc_insertion_point(class_scope:taurustrade.model.Portfolio)
  })
_sym_db.RegisterMessage(Portfolio)


# @@protoc_insertion_point(module_scope)
