# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: framework.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='framework.proto',
  package='taurustrade.message',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x66ramework.proto\x12\x13taurustrade.message\"3\n\x12GeneralRpcResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0f\n\x07message\x18\x02 \x01(\t\"G\n\x0eStrategyStatus\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tisRunning\x18\x02 \x01(\x08\x12\x14\n\x0cheartBeating\x18\x03 \x01(\x01\"F\n\rGatewayStatus\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tisRunning\x18\x02 \x01(\x08\x12\x14\n\x0cheartBeating\x18\x03 \x01(\x01*N\n\x0eOrderErrorCode\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x1a\n\x16UNSUPPORTED_PRICE_TYPE\x10\x01\x12\x13\n\x0f\x42\x41\x44_DATA_FORMAT\x10\x02*1\n\tRiskLevel\x12\x08\n\x04NONE\x10\x00\x12\x0b\n\x07WARNING\x10\x01\x12\r\n\tFORBIDDEN\x10\x02\x32\t\n\x07Gatewayb\x06proto3'
)

_ORDERERRORCODE = _descriptor.EnumDescriptor(
  name='OrderErrorCode',
  full_name='taurustrade.message.OrderErrorCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UNSUPPORTED_PRICE_TYPE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BAD_DATA_FORMAT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=238,
  serialized_end=316,
)
_sym_db.RegisterEnumDescriptor(_ORDERERRORCODE)

OrderErrorCode = enum_type_wrapper.EnumTypeWrapper(_ORDERERRORCODE)
_RISKLEVEL = _descriptor.EnumDescriptor(
  name='RiskLevel',
  full_name='taurustrade.message.RiskLevel',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WARNING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FORBIDDEN', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=318,
  serialized_end=367,
)
_sym_db.RegisterEnumDescriptor(_RISKLEVEL)

RiskLevel = enum_type_wrapper.EnumTypeWrapper(_RISKLEVEL)
UNKNOWN = 0
UNSUPPORTED_PRICE_TYPE = 1
BAD_DATA_FORMAT = 2
NONE = 0
WARNING = 1
FORBIDDEN = 2



_GENERALRPCRESPONSE = _descriptor.Descriptor(
  name='GeneralRpcResponse',
  full_name='taurustrade.message.GeneralRpcResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='taurustrade.message.GeneralRpcResponse.code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='taurustrade.message.GeneralRpcResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=91,
)


_STRATEGYSTATUS = _descriptor.Descriptor(
  name='StrategyStatus',
  full_name='taurustrade.message.StrategyStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='taurustrade.message.StrategyStatus.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isRunning', full_name='taurustrade.message.StrategyStatus.isRunning', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='heartBeating', full_name='taurustrade.message.StrategyStatus.heartBeating', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=164,
)


_GATEWAYSTATUS = _descriptor.Descriptor(
  name='GatewayStatus',
  full_name='taurustrade.message.GatewayStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='taurustrade.message.GatewayStatus.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isRunning', full_name='taurustrade.message.GatewayStatus.isRunning', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='heartBeating', full_name='taurustrade.message.GatewayStatus.heartBeating', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=236,
)

DESCRIPTOR.message_types_by_name['GeneralRpcResponse'] = _GENERALRPCRESPONSE
DESCRIPTOR.message_types_by_name['StrategyStatus'] = _STRATEGYSTATUS
DESCRIPTOR.message_types_by_name['GatewayStatus'] = _GATEWAYSTATUS
DESCRIPTOR.enum_types_by_name['OrderErrorCode'] = _ORDERERRORCODE
DESCRIPTOR.enum_types_by_name['RiskLevel'] = _RISKLEVEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GeneralRpcResponse = _reflection.GeneratedProtocolMessageType('GeneralRpcResponse', (_message.Message,), {
  'DESCRIPTOR' : _GENERALRPCRESPONSE,
  '__module__' : 'framework_pb2'
  # @@protoc_insertion_point(class_scope:taurustrade.message.GeneralRpcResponse)
  })
_sym_db.RegisterMessage(GeneralRpcResponse)

StrategyStatus = _reflection.GeneratedProtocolMessageType('StrategyStatus', (_message.Message,), {
  'DESCRIPTOR' : _STRATEGYSTATUS,
  '__module__' : 'framework_pb2'
  # @@protoc_insertion_point(class_scope:taurustrade.message.StrategyStatus)
  })
_sym_db.RegisterMessage(StrategyStatus)

GatewayStatus = _reflection.GeneratedProtocolMessageType('GatewayStatus', (_message.Message,), {
  'DESCRIPTOR' : _GATEWAYSTATUS,
  '__module__' : 'framework_pb2'
  # @@protoc_insertion_point(class_scope:taurustrade.message.GatewayStatus)
  })
_sym_db.RegisterMessage(GatewayStatus)



_GATEWAY = _descriptor.ServiceDescriptor(
  name='Gateway',
  full_name='taurustrade.message.Gateway',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=369,
  serialized_end=378,
  methods=[
])
_sym_db.RegisterServiceDescriptor(_GATEWAY)

DESCRIPTOR.services_by_name['Gateway'] = _GATEWAY

# @@protoc_insertion_point(module_scope)
