# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import framework_pb2 as framework__pb2
import market_pb2 as market__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = market__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = market__pb2.google.protobuf.timestamp_pb2
import trade_pb2 as trade__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = trade__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = trade__pb2.google.protobuf.timestamp_pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gateway.proto',
  package='taurustrade.framework',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rgateway.proto\x12\x15taurustrade.framework\x1a\x0f\x66ramework.proto\x1a\x0cmarket.proto\x1a\x0btrade.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1f\n\rSymbolRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t2d\n\x0eGatewayService\x12R\n\rSubscribeTick\x12$.taurustrade.framework.SymbolRequest\x1a\x19.taurustrade.message.Tick0\x01\x62\x06proto3'
  ,
  dependencies=[framework__pb2.DESCRIPTOR,market__pb2.DESCRIPTOR,trade__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_SYMBOLREQUEST = _descriptor.Descriptor(
  name='SymbolRequest',
  full_name='taurustrade.framework.SymbolRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='taurustrade.framework.SymbolRequest.symbol', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=144,
)

DESCRIPTOR.message_types_by_name['SymbolRequest'] = _SYMBOLREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SymbolRequest = _reflection.GeneratedProtocolMessageType('SymbolRequest', (_message.Message,), {
  'DESCRIPTOR' : _SYMBOLREQUEST,
  '__module__' : 'gateway_pb2'
  # @@protoc_insertion_point(class_scope:taurustrade.framework.SymbolRequest)
  })
_sym_db.RegisterMessage(SymbolRequest)



_GATEWAYSERVICE = _descriptor.ServiceDescriptor(
  name='GatewayService',
  full_name='taurustrade.framework.GatewayService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=146,
  serialized_end=246,
  methods=[
  _descriptor.MethodDescriptor(
    name='SubscribeTick',
    full_name='taurustrade.framework.GatewayService.SubscribeTick',
    index=0,
    containing_service=None,
    input_type=_SYMBOLREQUEST,
    output_type=market__pb2._TICK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GATEWAYSERVICE)

DESCRIPTOR.services_by_name['GatewayService'] = _GATEWAYSERVICE

# @@protoc_insertion_point(module_scope)
