# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strategy.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='strategy.proto',
  package='taurustrade.framework',
  syntax='proto3',
  serialized_options=b'\252\002\025AspNetCoregRpcService',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0estrategy.proto\x12\x15taurustrade.framework\x1a\x1bgoogle/protobuf/empty.proto\"G\n\x0eStrategyStatus\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tisRunning\x18\x02 \x01(\x08\x12\x14\n\x0cheartBeating\x18\x03 \x01(\x01\"\x1a\n\tStringPub\x12\r\n\x05value\x18\x01 \x01(\t2\n\n\x08StrategyB\x18\xaa\x02\x15\x41spNetCoregRpcServiceb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_STRATEGYSTATUS = _descriptor.Descriptor(
  name='StrategyStatus',
  full_name='taurustrade.framework.StrategyStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='taurustrade.framework.StrategyStatus.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isRunning', full_name='taurustrade.framework.StrategyStatus.isRunning', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='heartBeating', full_name='taurustrade.framework.StrategyStatus.heartBeating', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=141,
)


_STRINGPUB = _descriptor.Descriptor(
  name='StringPub',
  full_name='taurustrade.framework.StringPub',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='taurustrade.framework.StringPub.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=169,
)

DESCRIPTOR.message_types_by_name['StrategyStatus'] = _STRATEGYSTATUS
DESCRIPTOR.message_types_by_name['StringPub'] = _STRINGPUB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StrategyStatus = _reflection.GeneratedProtocolMessageType('StrategyStatus', (_message.Message,), {
  'DESCRIPTOR' : _STRATEGYSTATUS,
  '__module__' : 'strategy_pb2'
  # @@protoc_insertion_point(class_scope:taurustrade.framework.StrategyStatus)
  })
_sym_db.RegisterMessage(StrategyStatus)

StringPub = _reflection.GeneratedProtocolMessageType('StringPub', (_message.Message,), {
  'DESCRIPTOR' : _STRINGPUB,
  '__module__' : 'strategy_pb2'
  # @@protoc_insertion_point(class_scope:taurustrade.framework.StringPub)
  })
_sym_db.RegisterMessage(StringPub)


DESCRIPTOR._options = None

_STRATEGY = _descriptor.ServiceDescriptor(
  name='Strategy',
  full_name='taurustrade.framework.Strategy',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=171,
  serialized_end=181,
  methods=[
])
_sym_db.RegisterServiceDescriptor(_STRATEGY)

DESCRIPTOR.services_by_name['Strategy'] = _STRATEGY

# @@protoc_insertion_point(module_scope)
